import Card from "../card/Card";

export default function Cards({ forms }: any) {
  return (
    <div>
      {forms.map((el: any) => (
        <Card
          key={el.id}
          id={el.id}
          pregunta_1={el.pregunta_1}
          pregunta_2={el.pregunta_2}
          pregunta_2_otro={el.pregunta_2_otro}
          pregunta_3={el.pregunta_3}
          pregunta_4={el.pregunta_4}
          pregunta_5_telefono={el.pregunta_5_telefono}
          pregunta_5_correo={el.pregunta_5_correo}
          pregunta_6={el.pregunta_6}
          pregunta_7={el.pregunta_7}
          pregunta_8={el.pregunta_8}
          pregunta_9={el.pregunta_9}
          pregunta_10={el.pregunta_10}
          pregunta_11={el.pregunta_11}
          pregunta_12={el.pregunta_12}
          pregunta_13={el.pregunta_13}
          pregunta_14={el.pregunta_14}
          pregunta_15={el.pregunta_15}
          pregunta_16={el.pregunta_16}
          pregunta_17={el.pregunta_17}
          pregunta_18={el.pregunta_18}
          pregunta_19={el.pregunta_19}
          pregunta_20={el.pregunta_20}
          pregunta_21={el.pregunta_21}
          pregunta_22={el.pregunta_22}
          pregunta_23={el.pregunta_23}
          pregunta_24={el.pregunta_24}
          pregunta_25={el.pregunta_25}
          pregunta_26={el.pregunta_26}
          pregunta_27={el.pregunta_27}
          pregunta_28_diaria={el.pregunta_28_diaria}
          pregunta_28_semanal={el.pregunta_28_semanal}
          pregunta_28_mensual={el.pregunta_28_mensual}
          pregunta_29_yogurt_diaria={el.pregunta_29_yogurt_diaria}
          pregunta_29_yogurt_semanal={el.pregunta_29_yogurt_semanal}
          pregunta_29_yogurt_mensual={el.pregunta_29_yogurt_mensual}
          pregunta_29_kumis_diaria={el.pregunta_29_kumis_diaria}
          pregunta_29_kumis_semanal={el.pregunta_29_kumis_semanal}
          pregunta_29_kumis_mensual={el.pregunta_29_kumis_mensual}
          pregunta_29_cuajada_diaria={el.pregunta_29_cuajada_diaria}
          pregunta_29_cuajada_semanal={el.pregunta_29_cuajada_semanal}
          pregunta_29_cuajada_mensual={el.pregunta_29_cuajada_mensual}
          pregunta_29_queso_doble_crema_diaria={
            el.pregunta_29_queso_doble_crema_diaria
          }
          pregunta_29_queso_doble_crema_semanal={
            el.pregunta_29_queso_doble_crema_semanal
          }
          pregunta_29_queso_doble_crema_mensual={
            el.pregunta_29_queso_doble_crema_mensual
          }
          pregunta_29_queso_campesino_diaria={
            el.pregunta_29_queso_campesino_diaria
          }
          pregunta_29_queso_campesino_semanal={
            el.pregunta_29_queso_campesino_semanal
          }
          pregunta_29_queso_campesino_mensual={
            el.pregunta_29_queso_campesino_mensual
          }
          pregunta_29_leche_diaria={el.pregunta_29_leche_diaria}
          pregunta_29_leche_semanal={el.pregunta_29_leche_semanal}
          pregunta_29_leche_mensual={el.pregunta_29_leche_mensual}
          pregunta_29_quesos_madurados_diaria={
            el.pregunta_29_quesos_madurados_diaria
          }
          pregunta_29_quesos_madurados_semanal={
            el.pregunta_29_quesos_madurados_semanal
          }
          pregunta_29_quesos_madurados_mensual={
            el.pregunta_29_quesos_madurados_mensual
          }
          pregunta_29_requeson_diaria={el.pregunta_29_requeson_diaria}
          pregunta_29_requeson_semanal={el.pregunta_29_requeson_semanal}
          pregunta_29_requeson_mensual={el.pregunta_29_requeson_mensual}
          pregunta_29_arequipe_diaria={el.pregunta_29_arequipe_diaria}
          pregunta_29_arequipe_semanal={el.pregunta_29_arequipe_semanal}
          pregunta_29_arequipe_mensual={el.pregunta_29_arequipe_mensual}
          pregunta_29_otros={el.pregunta_29_otros}
          pregunta_30={el.pregunta_30}
          pregunta_31={el.pregunta_31}
          pregunta_32={el.pregunta_32}
          pregunta_33={el.pregunta_33}
          pregunta_34={el.pregunta_34}
          pregunta_35={el.pregunta_35}
          pregunta_36={el.pregunta_36}
          pregunta_36_otro={el.pregunta_36_otro}
          pregunta_37={el.pregunta_37}
          pregunta_37_otro={el.pregunta_37_otro}
          pregunta_38={el.pregunta_38}
          pregunta_38_otro={el.pregunta_38_otro}
          pregunta_39={el.pregunta_39}
          pregunta_40={el.pregunta_40}
          pregunta_40_cuales={el.pregunta_40_cuales}
          pregunta_41={el.pregunta_41}
          pregunta_42={el.pregunta_42}
          pregunta_43={el.pregunta_43}
          pregunta_44={el.pregunta_44}
          pregunta_44_cuales={el.pregunta_44_cuales}
          pregunta_45={el.pregunta_45}
          pregunta_45_como={el.pregunta_45_como}
          pregunta_46={el.pregunta_46}
          pregunta_46_como={el.pregunta_46_como}
          pregunta_47={el.pregunta_47}
          pregunta_48={el.pregunta_48}
          pregunta_49={el.pregunta_49}
          pregunta_50={el.pregunta_50}
          pregunta_51={el.pregunta_51}
          pregunta_52={el.pregunta_52}
          pregunta_53={el.pregunta_53}
          pregunta_54={el.pregunta_54}
          pregunta_55={el.pregunta_55}
          pregunta_56={el.pregunta_56}
          pregunta_57={el.pregunta_57}
          pregunta_58={el.pregunta_58}
          pregunta_59={el.pregunta_59}
          pregunta_60={el.pregunta_60}
          pregunta_60_cuales={el.pregunta_60_cuales}
          pregunta_61={el.pregunta_61}
          pregunta_61_cuales={el.pregunta_61_cuales}
          pregunta_62={el.pregunta_62}
          pregunta_63={el.pregunta_63}
          pregunta_64={el.pregunta_64}
          pregunta_64_otros={el.pregunta_64_otros}
          pregunta_65={el.pregunta_65}
          pregunta_66={el.pregunta_66}
          pregunta_67={el.pregunta_67}
          pregunta_68_energia={el.pregunta_68_energia}
          pregunta_68_gas={el.pregunta_68_gas}
          pregunta_69={el.pregunta_69}
          pregunta_69_porque={el.pregunta_69_porque}
          pregunta_70_yogurt_medida={el.pregunta_70_yogurt_medida}
          pregunta_70_yogurt_valor={el.pregunta_70_yogurt_valor}
          pregunta_70_kumis_medida={el.pregunta_70_kumis_medida}
          pregunta_70_kumis_valor={el.pregunta_70_kumis_valor}
          pregunta_70_cuajada_medida={el.pregunta_70_cuajada_medida}
          pregunta_70_cuajada_valor={el.pregunta_70_cuajada_valor}
          pregunta_70_queso_doble_crema_medida={
            el.pregunta_70_queso_doble_crema_medida
          }
          pregunta_70_queso_doble_crema_valor={
            el.pregunta_70_queso_doble_crema_valor
          }
          pregunta_70_queso_campesino_medida={
            el.pregunta_70_queso_campesino_medida
          }
          pregunta_70_queso_campesino_valor={
            el.pregunta_70_queso_campesino_valor
          }
          pregunta_70_leche_medida={el.pregunta_70_leche_medida}
          pregunta_70_leche_valor={el.pregunta_70_leche_valor}
          pregunta_70_quesos_madurados_medida={
            el.pregunta_70_quesos_madurados_medida
          }
          pregunta_70_quesos_madurados_valor={
            el.pregunta_70_quesos_madurados_valor
          }
          pregunta_70_requeson_medida={el.pregunta_70_requeson_medida}
          pregunta_70_requeson_valor={el.pregunta_70_requeson_valor}
          pregunta_70_arequipe_medida={el.pregunta_70_arequipe_medida}
          pregunta_70_arequipe_valor={el.pregunta_70_arequipe_valor}
          pregunta_70_otros={el.pregunta_70_otros}
          observaciones={el.observaciones}
          nombre_encuestado={el.nombre_encuestado}
          cedula_encuestado={el.cedula_encuestado}
          firma_encuestado={el.firma_encuestado}
          nombre_encuestador={el.nombre_encuestador}
          cedula_encuestador={el.cedula_encuestador}
          firma_encuestador={el.firma_encuestador}
        />
      ))}
    </div>
  );
}
